### ISSUE TITLE
testsuite red_black_tree: remove manual transformations from the session

### ISSUE THREAD

**Issue by Armael** [creusot-rs/creusot#1007]
Currently the proof of the red_black_tree example involves some manual transformations (`compute_hyp`) added in #1005 when upgrading alt-ergo from 1.4.3 to 1.5.3.
The reason is https://gitlab.inria.fr/why3/why3/-/issues/854 ; after the issue is addressed in why3 we should clean up the red_black_tree proof.

**Comment by xldenis** [comment]
Alternatively, we should consider providing custom proof strategies. The proof strategies that come with why3 are fairly arbitrary and tuned (if at all) for whyml, so it wouldn't be absurd for us to provide a custom set of transformations in `Auto_level_X`
