### ISSUE TITLE
Verification failure for rust code in recent commit

### ISSUE THREAD

**Issue by ruth561** [creusot-rs/creusot#1013]
I've recently started exploring Creusot. When attempting to verify the following Rust code snippet, verification fails:

```rust
#[ensures((^x) == 0i32)]
pub fn set_zero(x: &mut i32) {
	*x = 0;
}
```

In the Why3 IDE, the screen appears as shown below:

![スクリーンショット 2024-05-29 184914](https://github.com/creusot-rs/creusot/assets/87105992/18a69597-8923-4f78-b7b1-da18cfecba87)

When I moved to a commit from about two months ago ([3fdf297](https://github.com/creusot-rs/creusot/tree/3fdf29720144171393804e8168141a0f93217db4)) and tried, the verification succeeded. The Why3 IDE screen at that time looked similar to the image below.

![スクリーンショット 2024-05-29 173808](https://github.com/creusot-rs/creusot/assets/87105992/d80b0a8a-ca2c-45e7-bda4-eba6d9fcd59f)

I'd like to report this as an issue.

**Comment by xldenis** [comment]
Hi, thanks for reporting, I'll take a look when I get home later. Already, I can see that the proximal cause is that `resolve0` is opaque in your first screenshot, the proof isn't allowed to use the definition. In the interest of speeding up resolution, can you provide the _complete_ source code and process you used to generate your `mlcfg` file?

Notably, did you use `cargo creusot`, and is this a standalone crate? Did `cargo creusot` output any warnings or other log messages?

**Comment by xldenis** [comment]
So I wasn't able to reproduce using the `./mlcfg` script in the creusot repo, but I was using `cargo creusot`! Not sure why this occurs yet though.

**Comment by xldenis** [comment]
Ok, so for some reason, the opacity of `resolve` is different when using `cargo creusot` in that crate than when using `mlcfg`.

**Comment by xldenis** [comment]
We are probably losing something with the way we encode "opacity witnesses" in a multi-crate context and the way that we compile `creusot-contracts` for tests is sufficiently different to not materialize this. I think a simple fix will probably be to store opacity in crate metadata.

**Comment by ruth561** [comment]
Hi,

Thank you for your response. Here are the details regarding my environment and the contents of the MLCFG file.

First, this is a standalone crate with the following directory structure:

```
$ tree -a -I ".git|target|mir_dump"
.
├── .gitignore
├── Cargo.lock
├── Cargo.toml
├── rust-toolchain
└── src
    └── main.rs

1 directory, 5 files
```

The program is contained within src/main.rs, and the complete source code is as follows:

```rust
use creusot_contracts::*;

#[ensures((^x) == 0i32)]
pub fn set_zero(x: &mut i32) {
    *x = 0;
}

fn main() {}
```

I ran the verification using the command `cargo creusot why3 ide`. The log messages from this command are as follows:

```
$ cargo creusot why3 ide
    Checking creusot-practice v0.1.0 (/home/ruth/Documents/rust/creusot-practice)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.16s
Warning: Unrecognized source format `mlcfg`
Warning: Unrecognized source format `mlcfg`
Warning: Unrecognized source format `mlcfg`
Gdk-Message: 02:52:09.066: Window 0x563d86307e20 is a temporary window without parent, application will not be able to position it on screen.

(why3:48387): Gdk-CRITICAL **: 02:52:09.086: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
Warning: Unrecognized source format `mlcfg`
```

The MLCFG file is as follows:

```
module CreusotPractice_SetZero
  use prelude.Borrow
  use prelude.Int32
  predicate resolve0 (self : borrowed int32)
  val resolve0 (self : borrowed int32) : bool
    ensures { result = resolve0 self }
    
  use prelude.Int
  let rec cfg set_zero [#"../../src/main.rs" 4 0 4 28] [@cfg:stackify] [@cfg:subregion_analysis] (x : borrowed int32) : ()
    ensures { [#"../../src/main.rs" 3 10 3 22]  ^ x = (0 : int32) }
    
   = [@vc:do_not_keep_trace] [@vc:sp]
  var _0 : ();
  var x : borrowed int32 = x;
  {
    goto BB0
  }
  BB0 {
    [#"../../src/main.rs" 5 4 5 10] x <- { x with current = ([#"../../src/main.rs" 5 9 5 10] (0 : int32)) ; };
    assume { resolve0 x };
    [#"../../src/main.rs" 4 29 6 1] _0 <- ([#"../../src/main.rs" 4 29 6 1] ());
    return _0
  }
  
end
module CreusotPractice_Main
  let rec cfg main [#"../../src/main.rs" 8 0 8 9] [@cfg:stackify] [@cfg:subregion_analysis] (_1 : ()) : ()
   = [@vc:do_not_keep_trace] [@vc:sp]
  var _0 : ();
  {
    goto BB0
  }
  BB0 {
    [#"../../src/main.rs" 8 10 9 1] _0 <- ([#"../../src/main.rs" 8 10 9 1] ());
    return _0
  }
  
end
```

**Comment by ruth561** [comment]
I have to go to bed, so please understand if my reply is delayed.

**Comment by xldenis** [comment]
I've tested this locally and #1014 fixed it, closing for now.

**Comment by ruth561** [comment]
Thank you for the fix.
