### ISSUE TITLE
language file 'Coma' not found, when launching why3 ide 

### ISSUE THREAD

**Issue by Armael** [creusot-rs/creusot#1018]
```
$ cargo creusot why3 ide
language file for 'Coma' not found in directory /home/armael/recherche/creusot/_opam/share/why3/lang
```

this got broken by the merge of #968 , though the issue is probably on the side of the why3 coma branch that we now use.

**Comment by xldenis** [comment]
the solution is to copy the `coma.lang` file from the `mome` branch of why3 into the indicated directory. Why it isn't being installed with the other language definition files? I'm not sure. Perhaps deleting and recreating the opam switch fixes the issue?

**Comment by Armael** [comment]
it looks like it's just missing from the Makefile install step; I've submitted a MR on the why3 side...

**Comment by xldenis** [comment]
> it looks like it's just missing from the Makefile install step; I've submitted a MR on the why3 side...

Oh that's good.

**Comment by xldenis** [comment]
Fixed in latest versions of Coma.
