### ISSUE TITLE
Modular verification

### ISSUE THREAD

**Issue by mojeanmac** [creusot-rs/creusot#1067]
Verifying existing codebases must be done one module at a time. The current strategy of trusting individual functions and using `--focus-on` for individual strings might not scale for larger projects.
It would be great to have a way to focus on multiple modules, have "trusted" modules, or even have an option for creusot to ignore contractless functions.

**Comment by xldenis** [comment]
@jhjourdan @Armael what do you think? Molly is working on her undergraduate thesis and needs some way of integrating verified into a larger unverified project. 

I think having `#[trusted]` modules trust all descendents is a good solution but might still be too cumbersome. Perhaps the semantics of `--focus-on` could be adjusted? something like `--only=MODULE_PATH` (with repetition allowed) causing creusot to only lookup and generate proofs for functions in those modules?

**Comment by jhjourdan** [comment]
I put my veto on ignoring contractless functions. This makes too easy to forget to handle a function.

Trusted modules look like a good idea: this makes it easy to have modules handling e.g., some I/O operations or other "special" functions.

I'm don't like either `--focus-on` or other variants. Essentially, this makes it possible to assert stuff from the command line which makes it more difficult to review/identify the TCB. I'm not strongly opposed, though.

**Comment by xldenis** [comment]
> I'm don't like either --focus-on or other variants. Essentially, this makes it possible to assert stuff from the command line which makes it more difficult to review/identify the TCB. I'm not strongly opposed, though.

I understand and agree, I mostly see `--focus-on` as a development tool to make why3 ide faster (since it suffers from long files).

> Trusted modules look like a good idea: this makes it easy to have modules handling e.g., some I/O operations or other "special" functions.

I think this might be the best choice overall, and shouldn't be complicated to implement.

**Comment by mojeanmac** [comment]
Yes, I think that makes the most sense.

Also, while I'm not doing an undergrad thesis, I still hope to get what I'm working on published!
