### ISSUE TITLE
`rust-toolchain` is a symlink; bad for windows

### ISSUE THREAD

**Issue by Lysxia** [creusot-rs/creusot#1093]
Windows doesn't support symlinks, so it just sees `rust-toolchain` as a file containing the text "`ci/rust-toolchain`" instead of the contents of `ci/rust-toolchain`. Can we get rid of the symlink? Otherwise swap `rust-toolchain` and `ci/rust-toolchain`?

**Comment by xldenis** [comment]
Yes, I think we can absolutely get rid of the symlink, it might require a little work though to accomplish.

**Comment by jhjourdan** [comment]
swapping the two files is definitely an option.
