### ISSUE TITLE
Identifer names are unstable

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#1134]
Since @lysxia has moved us to hash based identifiers, they have become unstable, locally every proof regenerates at least one identifier causing proofs to be marked as obsolete / having detached goals. I don't know _why_ this occurs though, perhaps `StableHash` is not stable enough? Or we're too aggressively caching metadata?

**Comment by Lysxia** [comment]
Looking at the hash changes in #1133, do you know where the empty modules at the end of `type_invariants/borrows.coma` come from?

**Comment by xldenis** [comment]
You can also look at #1132, there are some failures due to `Invariant` but locally I observed some for other traits like `Clone`, `Eq` etc...

**Comment by xldenis** [comment]
Right now all I can think of is that `StableHash` is somehow platform dependent but the docs _explicitly_ say it shouldn't be. Alternatively, I notice you hash a `usize`, I suppose that could hypothetically b diff on 32 bit, but GH actions aren't 32 bit anyways...

**Comment by Lysxia** [comment]
FWIW when I build your PRs I get the same hashes as Github, i.e. no changes.

**Comment by xldenis** [comment]
That's what I figured unfortunately, suggesting a platform specific behavior since I'm on Mac.

**Comment by xldenis** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Platform-independence.20of.20StableHasher

It seems like the target host triple ends up somewhere in the hash thus leading do different behavior on mac and linux. I think it might be worth reverting #1123 until we find a platform independent solution.
