### ISSUE TITLE
Forbid uninhabited types

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#114]
In why3 types are always inhabited, to ensure that we don't cause issues or accidentally introduce unsoundness, we should forbid any empty type from being translated into why3, except for `!`. 

In particular this means ruling out:

1. Empty sums `enum Empty {}`
2. Co-recursive types `struct Stream<T> { hd: T, tl: Box<Stream<T>>}`. Ok, sure it's not _uninhabited_ but it has no finite inhabitant which is the same thing for us.

**Comment by Lysxia** [comment]
Just to make sure, in Rust there is no value of type `struct Stream<T> { hd: T, tl: Box<Stream<T>>}`, is there?

Otherwise we can close this as duplicate of #881
