### ISSUE TITLE
Simplifying 06_knights_tour

### ISSUE THREAD

**Issue by Lysxia** [creusot-rs/creusot#1148]
I'm looking at the [test cases that don't pass why3find](https://github.com/creusot-rs/creusot/issues/1002#issuecomment-2402610030) one by one to figure out what is missing.

The test `vector/06_knights_tour.rs` uses the transformation `use_th seq.FreeMonoid`, which imports a theory, like writing `use seq.FreeMonoid` in WhyML/Coma except that `use_th` is scoped to a specific goal, so it doesn't introduce unnecessary assumptions in other goals. For this test case, adding `use seq.FreeMonoid` before the definitions of `count_degree` and `knights_tour` makes `why3find prove` pass without any significant difference in other goals (all goals in the changed modules pass in < 1s). So the test case doesn't depend on the more fine-grained behavior of `use_th`.

1. Can we tell Creusot to insert `use` declarations from our contract annotations?
2. Do we need the more fine-grained behavior of `use_th` elsewhere? It seems that it should always be avoidable by introducing lemmas that are free to use `use` in their own proofs.

**Comment by jhjourdan** [comment]
An option could be to write the contents of `seq.FreeMonoid` in pearlite, and then individually import the required lemmas.

**Comment by Lysxia** [comment]
I am naively thinking of a `#[use(seq.FreeMonoid)]` attribute.

**Comment by xldenis** [comment]
I'm not a huge fan of that, where possible I want to avoid exposing why3
