### ISSUE TITLE
Variant checking unsoundly assumes precondition

### ISSUE THREAD

**Issue by jhjourdan** [creusot-rs/creusot#1204]
The following code proves false:

```rust
extern crate creusot_contracts;
use creusot_contracts::*;

#[logic]
#[requires(false)]
#[variant(x)]
fn evil(x: Int) -> Int {
    evil(-x) + 1
}

#[logic]
#[ensures(false)]
fn wrong() {
    proof_assert!{evil(1) == evil(-1) + 1};
    proof_assert!{evil(-1) == evil(1) + 1}
}
```

**Comment by jhjourdan** [comment]
We have two options to fix this
1- Guard the definition axiom by the precondition
2- Check the variant without assuming the preconditon, and only use the pre-condition to prove the post-condition (for logical functions). In this case, it is arguable whether we always require that preconditions of called functions hold.

**Comment by jhjourdan** [comment]
I would say that option 1- is weird, because functions which are not defined by using a variant are defined regardless of the precondition.

**Comment by xldenis** [comment]
> Check the variant without assuming the preconditon, and only use the pre-condition to prove the post-condition (for logical functions). In this case, it is arguable whether we always require that preconditions of called functions hold.

that sounds like we wouldn’t be able to write variants on Int anymore then since you need the precondition that the given int will be >= 0. 

What does why3 do here?

**Comment by jhjourdan** [comment]
> that sounds like we wouldn’t be able to write variants on Int anymore then since you need the precondition that the given int will be >= 0.

You can still write:

```rust
#[variant(x)]
fn f(x: Int) {
  if x >= 0 { blah f(x-1) blah } else { absurd}
}
```

> What does why3 do here?

Why3 uses let functions, which are undefined if the precondition is unsatisfied. The situation is somewhat incomparable since we only have one notion of logic function.

**Comment by jhjourdan** [comment]
We discussed this at the developers meeting: we choose option 1.
