### ISSUE TITLE
Add `#[lemma]`

### ISSUE THREAD

**Issue by shiatsumat** [creusot-rs/creusot#122]
I propose the `#[lemma]` annotation. This works like the following.
```rust
enum List { Cons(u32, Box<List>), Nil }
use List::*;

logic! {
    fn sum_list(l: List) -> Int {
        match l {
            Cons(a, l2) => Int::from(a) + sum_list(*l2),
            Nil => 0,
        }
    }
}

#[lemma]
#[variant(*l)]
#[ensures(sum_list(*l) >= 0)]
fn lemma_sum_list_nonneg(l: &List) {
    match l {
        Cons(_, l) => lemma_sum_list_nonneg(l),
        Nil => (),
    }
}
```

`#[lemma]` works the same as `#[pure]` in compilation to an MLCFG.
But it changes the function body to `{}` in making an executable.
(So `#[lemma]` can be given only to functions returning `()`.)

If we don't care about performance of the executable at all, this is not significant,
but I think this feature is fairly nice to have.

**Comment by shiatsumat** [comment]
Yeah, removing lemma function calls is not easy I think.
Making the function body of lemmas `{}` is much simpler, and I think the Rust/LLVM compiler usually removes trivial function calls in optimization.

**Comment by shiatsumat** [comment]
You mean, a new issue requesting the feature of ghost function calls?

**Comment by shiatsumat** [comment]
I don't think that direction works well.
First, you have to make sure to annotate every call of a lemma function as ghost, which can easily missed.
Also, for a lemma function to be logically safe, it should terminate for every input, so we should add a termination-check annotation to the lemma function anyway.

So I think `#[lemma]` is way more elegant and practically useful.

**Comment by jhjourdan** [comment]
In any case, `#[pure]` or `#[lemma]` would impose termination.

If we have support for ghost code, I think the idea would be to make `#[lemma]` calls ghost code, even if not annotated so.

**Comment by xldenis** [comment]
Exactly, the idea being when we have ghost code lemmas don't emit program symbols at all preventing any call from a non-ghost context
