### ISSUE TITLE
`cargo creusot config`: No such file or directory

### ISSUE THREAD

**Issue by arnaudgolfouse** [creusot-rs/creusot#1275]
`cargo creusot config` fails on a new project with
```
Error: why3find config failed

Caused by:
    No such file or directory (os error 2)
```
This seems to be because `why3find` is not available outside of creusot's directory. Since I installed why3find on a local switch inside that directory, it cannot find it elsewhere.

Looking at `cargo-creusot/src/why3find_wrapper.rs`, it seems this is also a problem for `cargo creusot prove`.

**Comment by Armael** [comment]
Ah yes, `why3find` should never be looked up from PATH except once in `creusot setup`. Afterwards, the path to the binary has been stored in the `Config.toml`, and `cargo creusot` should only use this path.
