### ISSUE TITLE
Feature Request: Mechanism to Create Axioms

### ISSUE THREAD

**Issue by r1ru** [creusot-rs/creusot#1310]
Currently, `#[trusted]` can only be applied to functions. It would be useful to have a feature that allows adding axioms at arbitrary locations, like `assume` in [Verus](https://verus-lang.github.io/verus/guide/develop_proofs.html). Users can use this for:

1. Debugging proofs.
2. Representing properties that can be guaranteed by means other than proofs.

**Comment by jhjourdan** [comment]
That's a duplicate of #657.

**Comment by jhjourdan** [comment]
In the meantime, one could create a trusted function, and call it at the appropriate place.
