### ISSUE TITLE
Use proper query system

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#158]
The core loop of Creusot is powered by a 'query' system: a HashMap which stores the results of translating functions. Structuring things as queries is quite natural when interacting with rustc which is itself structured as a query system. However, it could be very beneficial to move to a proper query system, like the one provided by [salsa](https://crates.io/crates/salsa).

**Comment by jhjourdan** [comment]
It's unclear what this would bring. Closing for now, but we will re-open if this appears to be useful.
