### ISSUE TITLE
Proper error handling

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#171]
At the moment, we have a rather [basic](https://github.com/xldenis/creusot/blob/master/creusot/src/ctx.rs#L223-L237) error reporting mechanism, as a result most of Creusot just panics upon an error. 

Obviously this sucks: we don't produce helpful error messages. The issue is that reporting an error requires having a `Session` on hand (wrapped by `TranslationCtx`). I propose we introduce a standard `Error` type which allows us to build up `Result<_, Error>` results and emit them at specific points.

**Comment by jhjourdan** [comment]
Isn't that fixed? We do have an `Error` type and we do emit (some) errors when the code is malformed.

Sure, there are still inputs that will end up in a panic, but this is rather a long-term work, that will never be really "finished".

**Comment by xldenis** [comment]
Yea, I guess we can consider this finished, I think we may want to end up adopting Rustc's convention of adding an `Error` variant to types so that we can provide better error recovery, but I agree that this is more of an 'aspriational' issue than anything concrete.
