### ISSUE TITLE
Unsafe checker

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#36]
Creusot can't actually verify unsafe code. For the moment, when you attempt to perform an 'unsafe operation' (raw pointer stuff, etc), an error is printed about how this operation is unsupported. Instead, we should check if a function contains unsafe code at all and just abort compilation, reporting a helpful message about unsafety.

**Comment by xldenis** [comment]
This is a bool field on basic blocks so it shouldn't be hard to check

**Comment by xldenis** [comment]
I don't know if this is super relevant in actuality. We can soundly support certain kinds of unsafe code (ie `get_unchecked`) and we already error or over approximate the kinds of unsafe code we can't support (ie: raw pointers).

**Comment by jhjourdan** [comment]
That being said, it would be good to have a systematic review of what happens if we use such or such unsafe feature. Do we panic? Do we repport a nice error message? Do we emit a relevant VC?

**Comment by xldenis** [comment]
Agreed, but this is not something we can enforce as a mere "reject unsafe code", I think our actual criterion is semantic not syntactic.
