### ISSUE TITLE
Further CI Improvements

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#379]
Thanks to @jhjourdan's #376 we can actually replay complex sessions in CI, but this is still rather unfinished business. There are a few further improvements we could make which would improve things:

- [x] Revert https://github.com/xldenis/creusot/pull/376/commits/f96de3a7232c8abcc108faa6ec885efb510a9bc7
- [x] Pre-package Alt-Ergo to avoid needing to install ocaml / built it on each CI run
- [x] Fail-fast if any sessions are obselete
- [ ] Set up a custom beefier runner
- [x] #368 
- [ ] Review and consolidate existing tests
   There are broadly two classes of tests in the suite: proofs which attempt to push the limits of what we do in creusot, and syntactic checks which ensure that we properly translate various parts of Rust and the various features of Creusot work as expected. The second category is poorly organized. We need to go over all the tests and consolidate them eliminaating redundant or useless tests.

**Comment by jhjourdan** [comment]
For now, the state of CI is ok-ish. Closing.
