### ISSUE TITLE
Add AddLogic and friends that can be used in pearlite.

### ISSUE THREAD

**Issue by jhjourdan** [creusot-rs/creusot#403]

**Comment by xldenis** [comment]
heterogeneous or homogeneous? I feel like homogenous would be nice but at the same time, I would like to be able to add a `u64` to an `Int`.

**Comment by jhjourdan** [comment]
For that reason, I think that should be heterogeneous.

**Comment by jhjourdan** [comment]
#1281 fixes this by providing homogeneous operators.

I am no longer convinced that heterogeneity is desirable. Rust does not have heterogeneity in the width and signedness of operands (it is impossible to add `u64` and `u32` directly in Rust), so it does not seem so natural to allow it in Pearlite. In addition, while it is reasonably clear that `u64` + `Int` would be an `Int`, do we want to allow e.g., `u64` + `u64`? If this is `u64`, then we don't know (yet) how to handle overflows, but if this is `Int`, then we commit to never allow machine arithmetic in pearlite.

**Comment by jhjourdan** [comment]
So I would prefer leaving heterogeneity for the future, when we will have concrete use cases that requires it.
