### ISSUE TITLE
Ensures and requires clause order is reversed when translated into Why3

### ISSUE THREAD

**Issue by jhjourdan** [creusot-rs/creusot#421]

**Comment by xldenis** [comment]
This is still an issue in Coma, though its importance is less clear there.

**Comment by jhjourdan** [comment]
I guess the problem is the same for `invariant` closes?

**Comment by jhjourdan** [comment]
Is it really still reversed? `contract_clauses_of` seems to contain a call to `rev` to reverse the order....

**Comment by Lysxia** [comment]
Closed in #1229
