### ISSUE TITLE
Mismatched types error in ghost macro

### ISSUE THREAD

**Issue by voidc** [creusot-rs/creusot#447]
The following code produces a mismatched types error:
```rust
fn foo() {
    let mut c: Ghost<usize> = ghost! { 0 };
    c = ghost! { *c + 1 };
    // expected reference, found `usize`
}
```
However, when surrounding the expressing with parentheses, the code compiles:
```rust
fn foo() {
    let mut c: Ghost<usize> = ghost! { 0 };
    c = ghost! { (*c + 1) };
}
```

**Comment by xldenis** [comment]
Another issue I've found: the `ghost!` macro does not work well when storing ghost values in types, it doesn't compile properly when compiling in passthrough mode (not creusot).

**Comment by xldenis** [comment]
Fixed if you rename `Ghost` to `Snapshot`.
