### ISSUE TITLE
Default trait derives can cause crashes

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#455]
Currently, the default derivations for traits like `PartialEq` and `Hash` can crash creusot. 

We should 
- [ ] Provide custom derives which prove the specifications
- [ ] Ensure the default macros don't cause a crash
- [ ] Warn when a user uses the default macro with no specification rather than the specifying one.

**Comment by jhjourdan** [comment]
I dispatched the items to other issues, so closing this one.
