### ISSUE TITLE
Cryptic Why3 error when using open mutual recursion

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#459]
I just encountered an annoying error in why3 because of 'open' mutual recursion:

If we define an instance of `Model` for `Box` (which makes sense to do), then the following code cannot compile:

```
enum A { Cons(Box<A>), Nil }

impl Model for A {
...
#[logic]
fn model(self) -> Self::ModelTy {
   match self {
   A::Cons(a) => a.model() + 1,
   A::Nil => 0
}
}
```

The reason is that we need to use a version of `model` for box with it's internal call instantiated to `model` from `A` but creates a cycle in the clone graph. 

I know how to catch the error early but this is something that would be nice to fix properly.

**Comment by jhjourdan** [comment]
Fixed in #1228 .
