### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by dewert99** [creusot-rs/creusot#496]
It would probably be useful to allow uses to manually specify triggers for laws and quantifiers to help avoid matching loops.  Note: Why3 already supports this https://why3.lri.fr/doc/syntaxref.html#grammar-token-triggers

**Comment by xldenis** [comment]
You're right, though for whatever reason, manually specifying triggers seems to very much not be in the cultural norms of why3, you'll be hard pressed to find any manual triggers in the standard library or why3 benchmarks.
