### ISSUE TITLE
Make verified conditions available to the optimizer

### ISSUE THREAD

**Issue by LevitatingLion** [creusot-rs/creusot#508]
I would like to make the fact that certain conditions are verified to always hold available to the optimizer. With this, things like bounds checks or `unwrap`s that are verified to never fail can be optimized away completely.

For this purpose I came up with the following macro `proved_assume!`:

```rust
macro_rules! proved_assume {
    (unsafe { $($cond:tt)* }) => {{
        let cond = { $($cond)* };

        // Assert the condition in debug builds, to make it available to the verifier
        #[cfg(any(debug_assertions, feature = "contracts"))]
        ::core::assert!(cond);

        // Assume the condition in release builds. This is only sound if the condition was verified.
        #[cfg(not(debug_assertions))]
        if !cond {
            unsafe { ::core::hint::unreachable_unchecked() };
        }
    }};
}
```

It requires the argument to be wrapped in `unsafe` to signify that it may lead to unsoundness in release builds if the condition is not actually verified. It can be used like this:

```rust
// Prove that the access is in bounds during verification
proved_assume!(unsafe { i < arr.len() });
// The compiler will be able to remove this bounds check
let elem = arr[i];
```

Or like this:

```rust
// Perform the access with bounds checks
let elem = arr.get(i);
// Prove that the access is in bounds during verification
proved_assume!(unsafe { elem.is_some() });
// The compiler will be able to remove the above bounds check and this `unwrap`
let elem = elem.unwrap();
```

Is this something you would want to include in Creusot?

**Comment by suhr** [comment]
Would be cool, but right now nothing tracks that assertions are actually proved: you need to manually run `cargo creusot` and then manually invoke solvers in why3 ide. So before implementing this, you need a content addressable map from the source code to the proof status.

**Comment by jhjourdan** [comment]
Instead of "making this information available to the compiler", what about manually using unsafe (but verified) versions of unwrap/get/get_mut when the preconditions are verified by Creusot?

**Comment by dewert99** [comment]
We would probably want an extern spec for `::core::hint::unreachable_unchecked()` (requires false) as a building block.  This would be useful on its own (for example when pattern matching) and could also be used to build `proved_assume`:
```rust
macro_rules! proved_assume {
    (unsafe { $($cond:tt)* }) => {{
        let cond = { $($cond)* };
        if !cond {
            unsafe { ::core::hint::unreachable_unchecked() };
        }
    }};
}
```

**Comment by xldenis** [comment]
Is it not translated to `absurd`? It should be. By the way I believe rust has a `assume` intrinsic which you could use here.

**Comment by dewert99** [comment]
I just check and it is, I'm not sure where/if this is documented, I usually just look at `creusot-contracts` to see what is supported

**Comment by xldenis** [comment]
Yea, this wouldn't be documented in `creusot-contracts` as the intrinsic will get lowered to a specific MIR construct, not a function call.

**Comment by jhjourdan** [comment]
About the `proved_assume` macro: we need to make sure that it is still unsafe. I'd like to maintain the invariant that any piece of Rust code that does not contain `unsafe` is indeed safe, even if not proved by Creusot.

The reason for this is that Creusot proofs sometimes requires preconditions, which may or may not be proved valid by unproved clients of a library. If the safety relies on such a precondition, then the whole program is potentially unsafe.

**Comment by LevitatingLion** [comment]
> About the proved_assume macro: we need to make sure that it is still unsafe.

Absolutely! We could require syntax like `proved_assume!(unsafe { i < arr.len() })` or even `unsafe { proved_assume!(i < arr.len()) }`. The latter can be required e.g. by calling an `unsafe` dummy function in the expansion of `proved_assume`, or just by omitting the `unsafe` block around `unreachable_unchecked`.

> Instead of "making this information available to the compiler", what about manually using unsafe (but verified) versions of unwrap/get/get_mut when the preconditions are verified by Creusot?

I think I actually prefer this approach, as that's also what you would do in non-verified Rust code. Then we don't need a dedicated `proved_assume!`, we can just add specifications of the unsafe accessors (`unwrap_unchecked`, `get_unchecked`, `get_unchecked_mut` and the like)

**Comment by jhjourdan** [comment]
This can be done in library code, so we don't consider this as a bug. PRs welcome!
