### ISSUE TITLE
Type inference fails on specific reuse of a reference

### ISSUE THREAD

**Issue by jhaye** [creusot-rs/creusot#574]
I took a look at the [all zero exercise](https://github.com/xldenis/creusot-exercises/blob/master/exercises/04_all_zero.rs). When adding the following loop invariant `#[invariant(bounds, @i <= (@*v).len())]` while `v` is also referenced in the already existing invariant, I get the following error:

```
error[E0282]: type annotations needed
  --> 04_all_zero.rs:13:5
   |
13 |     #[invariant(proph_const, ^v == ^old_v.inner())]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
   |
   = note: this error originates in the attribute macro `invariant` (in Nightly builds, run with -Z macro-backtrace for more info)

error[creusot]: internal error
```

Running with `-Z macro-backtrace` isn't very illuminating and interestingly, other invariants like `#[invariant(prev_all_zero, forall<j: Int> 0 <= j && j < @i ==> (@v)[j] == 0u32)]` that also use `v` do not produce this error.

I have tried some variations of the first invariant:

1. `#[invariant(bounds, @i <= (@v).len())]`
2. `#[invariant(bounds, @i <= (@^v).len())]`
3. `#[invariant(bounds, @i <= @(v.len()))]`

They all produce the same outcome.

**Comment by jhjourdan** [comment]
Won't fix.
