### ISSUE TITLE
Check trait constraints when checking reffinements of extern specs for trait methods 

### ISSUE THREAD

**Issue by jhjourdan** [creusot-rs/creusot#587]
extern specs for trait methods can add further traits constraints that do not appear in the original trait definition.

When we implement such a trait, we should check that: 
- We do indeed check the refinement in that case
- The additional trait constraints are indeed satisfied for the new implementation.

**Comment by xldenis** [comment]
This definitely occurs since its the source of a bunch of annoying errors when trying to use creusot.
