### ISSUE TITLE
cargo creusot ignores source code changes

### ISSUE THREAD

**Issue by champignoom** [creusot-rs/creusot#828]
After running `cargo creusot`, `target/debug/` is created, where there's the mlcfg file.

But then if one modifies the code and run `cargo creusot` again, nothing in `target/debug/` is changed.

Of course, one can remove `target/` before running `cargo creusot` each time, but that causes unnecessary recompilation of creusot-contract, pearlite-syn, unicode-indent, and other external crates.
Is there a more effective workflow than this?

Thanks.

**Comment by xldenis** [comment]
Sorry,  I thought I had already answered but I guess my answer never went through. 

It's weird because it _should_ be picking up your source code changes, it does it my personal projects using `cargo creusot`. Could you post exactly the command and set up of your project?

as a short term patch you can also do `cargo clean -p crate-name` to avoid cleaning _everything_ that way only your final crate is cleaned.

**Comment by champignoom** [comment]
The problem seems to be reproduced only when `creusot_contracts::*` is not used, so:

```rust
extern crate creusot_contracts;
use creusot_contracts::*;

fn main() {
    // proof_assert!(true);
    let a = 9811111i32;
    let b = a*a;
}
```

With the `proof_assert!` commented out, `cargo creusot` ignores any change on the value of `a` and leaves the mlcfg file unchanged.

**Comment by xldenis** [comment]
Huh, that is odd? I'm not sure where to start digging. I think perhaps the best thing we could do is fully seperate the `cargo creusot` and `cargo build` directories. Could you try seeing if using `CARGO_TARGET_DIR` helps? 

1. `CARGO_TARGET_DIR=foo cargo creusot`
2. Make change
3. `CARGO_TARGET_DIR=foo cargo creusot`
4. Updated output?

**Comment by champignoom** [comment]
Tried in vain.

And it's becoming weirder. It looks like the problem is only reproduced when using vscode to edit the source. If I edit it with `sed -i` for example, the problem disappears.

**Comment by champignoom** [comment]
OK, I'm not sure why but `touch src/main.rs && cargo creusot` fixes the problem.

**Comment by champignoom** [comment]
According to the result of`stat src/main.rs`, vscode does update the atime and ctime when `src/main.rs` is edited, so `touch src/main.rs` shouldn't make that much of a difference.

I'm not sure if this is a problem of macos or vscode or creusot, but `cargo run` does not suffer from this problem.

**Comment by xldenis** [comment]
Well, Creusot doesn't actually do dependency management itself, it uses `cargo` for that. It's possible we're doing something wonky but apart from sharing the target dir I have no idea what that could be.

**Comment by xldenis** [comment]
I'm going to label this as a bug, but basically `cargo creusot` should use its own target inside of `target/` not piggyback on `debug`.

**Comment by Lysxia** [comment]
This should be fixed now, although we now have the opposite problem that we rebuild too much sometimes #1218
