### ISSUE TITLE
Fix resolution of partially initialized values

### ISSUE THREAD

**Issue by voidc** [creusot-rs/creusot#848]
When moving a single field of an aggregate value, we still consider the local initialized. As a consequence, we sometimes resolve locals that are only partially initialized. Combined with type invariants, this leads to unprovable assertions, as we structurally assert the invariant of the uninitialized field (that now contains `any`). If the aggregate type has a user invariant, this behavior works as intended, as we want to prevent moving out of such types. However, if the invariant of the aggregate type is merely structural, the current behavior is overly restrictive. There are two potential solutions:

- If we move a field of a type without user invariant, assume the invariant of the `any` value assigned to the field holds.
- Perform the initialization analysis on a per-place basis and only resolve initialized places.

**Comment by xldenis** [comment]
@jhjourdan we should be able to close this now that we have place-based resolution no?

**Comment by jhjourdan** [comment]
Indeed.
