### ISSUE TITLE
relative locations/spans are broken when using `cargo creusot`

### ISSUE THREAD

**Issue by Armael** [creusot-rs/creusot#944]
When using `cargo creusot` the spans/locations are currently broken:
- spans using relative paths are the default (which indeed seems necessary to allow committing mlcfgs into git)
- spans use relative paths that assume that the `.rs` file and related `.mlcfg` file are next to each other
- this assumption holds for the creusot testsuite (AFAICT the test harness calls creusot-rustc directly, in a way where the .mlcfg ends up next to the .rs file)
- but it *does not* hold for `cargo creusot` invocations, which generate the .mlcfg files in `target/debug/`.

I'm not sure how to properly fix the issue:
- adding `../../` to the relative paths would fix it for `cargo creusot` but break the testsuite
- it's also not clear that `target/debug` where we want the .mlcfg to be; if we want to check them into git then they should probably be somewhere else (I assume `target/` is usually in .gitignore). 
- maybe the relative paths could assume that we're in a `cargo creusot` setup, and additionally add an option to creusot-rustc to explicitly specify the relative path of the .rs file wrt the .mlcfg file, that the testsuite harness would use.

Any ideas?
Provided we agree on the design for the solution I'm happy to try and implement it.

**Comment by xldenis** [comment]
> maybe the relative paths could assume that we're in a cargo creusot setup, and additionally add an option to creusot-rustc to explicitly specify the relative path of the .rs file wrt the .mlcfg file, that the testsuite harness would use.

I think something like this is reasonable to provide a 'relative from' option.
