### ISSUE TITLE
unbound type symbol 'opaque_ptr' in why3 ide

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#949]
### Discussed in https://github.com/creusot-rs/creusot/discussions/948

<div type='discussions-op-text'>

<sup>Originally posted by **nishanthkarthik** February 21, 2024</sup>
Hi! I built creusot by following the steps at https://github.com/creusot-rs/creusot and created an empty rust project with the same toolchain version to test a contract. When I run `cargo creusot`, I see an mlcfg file generated but this is not loaded by the why3 ide

I am using the ide script from the repo root. 

```
Unrecognized source format `mlcfg`
File "../ghostptrtoken_test-bin.mlcfg", line 67, characters 39-49: unbound type symbol 'opaque_ptr'
```

The prelude pointed to by the ide script does point to a type in prelude.mlw. 

The snippet I'm trying to use to test creusot contract is

```rs
use creusot_contracts::*;
use creusot_contracts::ghost_ptr::GhostPtrToken;
use ::std::ops::Deref;
use ::std::ptr::null;

fn main() {
    let mut tok = GhostPtrToken::new();
    let b = Box::new(1);
    let p = tok.ptr_from_box(b);
    let mut r = tok.ptr_to_box(p);
    *r += 5;
}
```

**Comment by xldenis** [comment]
@nishanthkarthik I've reproduced this locally, it seems to be a bug with the handling of type invariants. I don't think it will be complex to fix though.

**Comment by nishanthkarthik** [comment]
Thank you for the fix
