### ISSUE TITLE
`cargo creusot setup` doesn't work on Mac

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#967]
Currently there's a bug in Why3 which causes it to mishandle paths with spaces in them, and on Mac the cargo creusot files are stored in `~/Library/Application Support`. @Armael and I debugged it and found the fixes in why3.

**Comment by Armael** [comment]
This should be solved now (with the why3 commit indicated in the .opam file). Could you check that it indeed works on your computer?

**Comment by xldenis** [comment]
yep!
