### ISSUE TITLE
Upgrade testsuite to alt-ergo 2.5.3

### ISSUE THREAD

**Issue by Armael** [creusot-rs/creusot#978]
Thanks to @bclement-ocp we'll soon have redistribuable binary builds of alt-ergo to use in `creusot setup`. (cf https://github.com/OCamlPro/alt-ergo/pull/1045).

Before that we need to upgrade creusot's testsuite to use the latest alt-ergo version, 2.5.3.

Xavier has a tool to do this kind of solver upgrade in batch: https://github.com/xldenis/why3-tools/ (https://github.com/xldenis/why3-tools/blob/master/bin/upgrade.ml)

invocation example:
```dune exec why3_tools -- upgrade -L/Users/xavier/Code/creusot/prelude/ --upgrade=Alt-Ergo,2.4.1=Alt-Ergo,2.4.2 ~/Code/creusot/creusot/tests/should_succeed/bug/271.mlcfg```

**Comment by Armael** [comment]
(currently looking at this... there are a few quirks related to creusot setup that need solving, but no fundamental blocker afaict)

**Comment by Armael** [comment]
Implemented in #1005 (using some manual transformations in red_black_tree that could be removed after https://gitlab.inria.fr/why3/why3/-/issues/854 is fixed).

**Comment by xldenis** [comment]
Do you want to close this issue now? Or after the why3 issue is closed?

**Comment by Armael** [comment]
I'll close this now, and open a different issue to remember to clean up the red_black_tree session eventually.
