### ISSUE TITLE
README instructions for setting up why3 and alt-ergo seem flawed

### ISSUE THREAD

**Issue by pnkfelix** [creusot-rs/creusot#981]
In the following text of the README:

https://github.com/creusot-rs/creusot/blob/329deaed28e8810023e5b92de51513d5cc147e23/README.md?plain=1#L43-L50

it claims that just doing `opam switch ...` followed by `eval $(opam env)` will suffice to build why3, alt-ergo, and their ocaml dependencies.

But when I tried that, I saw no evidence of those components being built.

I am not an OCaml programmer and don't know anything about `opam`, but from my inspection of the `opam --help` leads me to believe that `opam switch` and `opam env` are not sufficient here.

Is it possible that some step was left out of https://github.com/creusot-rs/creusot/commit/72349a0cb5bcca7900b5efbec2c717f256f5c820 ?

**Comment by Armael** [comment]
Hi! Thanks for the report. These commands are supposed to be the right ones, but they need to be run *from the creusot sources directory*: this way, opam will pick up the `creusot-deps.opam` file and install what's specified in there, including why3 and alt-ergo at the correct versions.
Could you check that you were indeed running the two commands from the creusot directory?
To be explicit, the following should work:
```
git clone https://github.com/creusot-rs/creusot
cd creusot
opam switch create -y . ocaml.4.14.1
eval $(opam env)
# check the install
which why3  # should return /path/to/creusot/_opam/bin/why3
why3 --version  # should return version 1.7.1+git 
# then the rest of the instructions from the README to complete the install
```

**Comment by pnkfelix** [comment]
hunh.

a fresh checkout did work as you described.

I must have been doing something differently (its hard for me to be sure what, in part because I was working against a previous checkout that still had old build artifacts in it).

In any case, I'll close this for now, since its clearly incorrect.

**Comment by Armael** [comment]
Alright, no worries. I've taken this opportunity to try to make the installation instructions a bit clearer in #985 .
