### ISSUE TITLE
Type invariants incorrectly asserted for partially-initialized values. 

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#990]
The following code:
```
        let (left, remn) = self.split(i);
        let (_, right) = remn.split(len);
```

generates something like the following:
```
res <- split i;
left <- res.0;
res <- (any, res.1);
remn <- res.1;
res <- (res.0, any);
assert { invariant res };
```
however: at that point the invariant is not initialized!! and thus cannot be proved.

**Comment by voidc** [comment]
This looks related to #848

**Comment by xldenis** [comment]
@jhjourdan is this fixed as a side-effect of the place based resolution work?

**Comment by jhjourdan** [comment]
Indeed.
